### ISSUE TITLE
modifier is called infinitely on Safari

### ISSUE THREAD

**Issue by mydea** [ember-modifier/ember-modifier#11]
I have a modifier like this:

```js
import { modifier } from 'ember-modifier';

export function resizeObserver(
  element,
  [onResize],
  { hasResizeObserver = 'ResizeObserver' in window }
) {
  // Note: The resize observer will also run initially
  // If it is not supported, we only call it once, 
  // but it will not trigger on actual resizing
  // Note: This can be overwritten for tests
  if (!hasResizeObserver) {
    let width = Math.floor(element.offsetWidth);
    onResize({ width, element, runCount: 0 });
    return;
  }

  let runCount = 0;
  let previousWidth;
  let resizeObserver = new ResizeObserver(() => {
    let width = Math.floor(element.offsetWidth);

    if (width === previousWidth) {
      return;
    }

    onResize({ width, element, runCount });
    runCount++;
    previousWidth = width;
  });

  resizeObserver.observe(element);

  return () => resizeObserver.disconnect();
}

export default modifier(resizeObserver);
```

Used like this:

```hbs
<FTable
  @data={{this.sortedData}}
  {{resize-observer this.onResizeTable}}
>
```

On Safari, this ended up calling the modifier function infinitely, completely crashing the page.
I checked a bit, and it called the function with the same `element`, all the time until Ember threw an "Infinite rendering invalidation...." error.

On Chrome & Firefox, it worked as expected (only calling the method once).
Not sure if I'm doing anything wrong here, but I can't really see any other way to do this.
I ended up adding a `WeakMap` to hold the `element` and comparing that, but I guess that's not how it's supposed to work?

**Comment by chriskrycho** [comment]
@mydea thanks for reporting! Can you make a minimal example—that is, whatever is the *smallest* amount of code that does this? It seems like it's probably *something* about the use of `ResizeObserver`, but it's not obvious to me *what*, and having the least amount of code involved would help narrow it down.

**Comment by mydea** [comment]
It's sadly a bit tricky for me to debug this, as I don't have Safari - I need to borrow a device from a coworker to try it out which is.. kind of hard these days :grimacing:

I am about 80% sure that it behaved the same with a more minimal example:

```js
import { modifier } from 'ember-modifier';

export function resizeObserver(
  element,
  [onResize],
) {
  let resizeObserver = new ResizeObserver(() => {
    onResize(element);
  });

  resizeObserver.observe(element);

  return () => resizeObserver.disconnect();
}

export default modifier(resizeObserver);
```

If you have a Macbook, maybe you could try that. It was really easy for me (at the time) to reproduce, as it happened every time.

**Comment by chriskrycho** [comment]
For what it's worth, I cannot reproduce this. Just fired it up in Safari with the above and a backing controller which just measures the size of the `div` it's applied to, like this:

```js
import Controller from '@ember/controller';
import { tracked } from '@glimmer/tracking';
import { action } from '@ember/object';

export default class Application extends Controller {
  @tracked size: Size = {
    height: 'unknown',
    width: 'unknown',
  };

  @tracked runCount = 0;

  @action onResize({ width, element, runCount }) {
    this.size = {
      height: element.clientHeight,
      width: width,
    };
    this.runCount = runCount;
  }
}
```

This works fine in both 13.1 and Tech Preview Release 106 (Safari 13.2).

It's possible that (a) Safari fixed a bug in the meantime or that (b) there's a problem in the action that you're connecting it to.

**Comment by mydea** [comment]
I have tried rolling the change back in our app and tried it again in Safari on a coworkers Macbook, and it seemed to be working now. So maybe Safari really fixed something - either way, as I can't reproduce it anymore either, I will close this - thank you anyhow for looking into it!
