### ISSUE TITLE
Changelog missing

### ISSUE THREAD

**Issue by Turbo87** [ember-modifier/ember-modifier#14]
There does not seem to be a `CHANGELOG.md` file in this repo and https://github.com/ember-modifier/ember-modifier/releases is also not helpful.

@pzuraq what changes were introduced in the latest releases?

**Comment by Turbo87** [comment]
sorry, on second reading, this sounds more rude than intended... 😅 

I'm just trying to figure out what changed and a changelog would be very much appreciated. Happy to show you how to generate one using lerna-changelog for example :)

**Comment by pzuraq** [comment]
No it's my bad, I have been meaning to learn lerna-changelog and get in the habit of using it in general for a while now and keep putting it off. I'll make it a priority in the coming weeks, now that Octane work is finally cooling off.

v1.0.3 contained a bugfix for IE11, I believe that was the only change.

**Comment by elwayman02** [comment]
I can help with this, @pzuraq! I'll submit an RB that matches this:

https://github.com/elwayman02/ember-scroll-modifiers/pull/10

Then you just need `GITHUB_AUTH` and `GITHUB_TOKEN` defined locally for lerna and release-it to read, respectively, and everything works seamlessly!

Here's an example of the result:

https://github.com/elwayman02/ember-scroll-modifiers/commit/58217364699cb79a8b5c22c265db4188a2257bbf
