### ISSUE TITLE
expected to be able to return a clean up function from did-insert callback

### ISSUE THREAD

**Issue by tomwayson** [ember-modifier/ember-modifier#18]
I expected that if I returned a function from the `did-insert` callback that it would would be called before the element was removed from the DOM the same way that you can do w/ custom modifiers:

https://github.com/ember-modifier/ember-modifier#example-with-cleanup

However, I don't see my clean up function being invoked. I can't tell from the docs in this repo if my expectation is correct or not.

If not, should I be using `will-destroy` instead of returning a clean up function?

**Comment by pzuraq** [comment]
`{{did-insert}}` is not related to this addon and API for writing modifiers, it is its own modifier that just runs a function when the element is inserted. It doesn't do anything with the return value.

You should use `{{will-destroy}}` to clean up after `{{did-insert}}`, or you can write your own modifier instead.

**Comment by tomwayson** [comment]
Thank you @pzuraq, I meant to open this issue over in https://github.com/emberjs/ember-render-modifiers but accidentally opened it here (too many tabs open).
