### ISSUE TITLE
Getting the previous value for an argument from didReceiveArguments

### ISSUE THREAD

**Issue by burritoIand** [ember-modifier/ember-modifier#19]
With the move away from component lifecycle hooks towards using element modifiers, I am investigating how I can port some code over. The existing code uses an addon called [ember-did-change-attrs](https://github.com/workmanw/ember-did-change-attrs) that effectively wraps Component.didReceiveAttrs and is called when the component attributes changed, similarly to what the class modifier is doing with didReceiveArguments.

However with that package it also provides a `changes` argument that contains both the _old_ and the _new_ argument values so that they can be compared etc.

How can I access the old/previous value within `didReceiveArguments`? Is this something that could be added to the behavior of the modifier?

edit: I realize I can just track the value manually in the modifier class (e.g. Modifier.lastValue), but was curious if there's another way?

**Comment by pzuraq** [comment]
The recommendation is to track the previous value, like you mentioned. I do think a utility for doing this sort of simple memoization would be good, but not sure what the best pattern would be far that yet (and I don't think it would be related to this library necessarily).

**Comment by burritoIand** [comment]
ok gotcha, I was able to get it working by tracking the last value so that works :) thanks
