### ISSUE TITLE
README - Class modifier - Arguments destruct incorrect

### ISSUE THREAD

**Issue by MrChocolatine** [ember-modifier/ember-modifier#21]
I am not quite sure the arguments can be destructured from the Class itself :
https://github.com/ember-modifier/ember-modifier/blob/96f64dfb5036d99a3b4648a71db071077e8f60de/README.md#L181

I guess it should be the same as :
https://github.com/ember-modifier/ember-modifier/blob/96f64dfb5036d99a3b4648a71db071077e8f60de/README.md#L171

**Comment by pzuraq** [comment]
Yep, that looks correct to me. PR welcome here, I'll see if I can get it fixed soon but pretty busy at the moment

**Comment by MrChocolatine** [comment]
I completely forgot.

**Comment by joshkg** [comment]
> `this` refers to the Class, not an Array, therefore Array destructuring is not what we want.

@MrChocolatine Agree that it should have been object destructuring, but the question is really about the logic -- I believe the reason we were targeting `this` was to check for previously set `event` and `handler` properties as noted above

**Comment by MrChocolatine** [comment]
> > `this` refers to the Class, not an Array, therefore Array destructuring is not what we want.
> 
> @MrChocolatine Agree that it should have been object destructuring, but the question is really about the logic -- I believe the reason we were targeting `this` was to check for previously set `event` and `handler` properties as noted above

I see, sorry I misunderstood your message then!

That is actually a fair point!

1. The modifier is called a first time, everything runs correctly.
1. The arguments are updated, `didReceiveArguments()` gets called.
1. `removeEventListener()` gets called, we might actually prefer to use/remove the `event` and `handler` already stored on `this`
1. `addEventListener()` will run using the updated arguments.

**Comment by joshkg** [comment]
@MrChocolatine Right! So I believe it will help clarify this example to either remove the logic that is storing the `event` and `handler` on the instance, and always destructure them from `this.args.positional`, OR retain the logic that is storing them and update the `removeEventListener` to destructure `event` and `handler` from `this`.

**Comment by MrChocolatine** [comment]
> retain the logic that is storing them and update the `removeEventListener` to destructure `event` and `handler` from `this`.

Personally, I would vote for this.

**Comment by MrChocolatine** [comment]
Let's give it a try:
https://github.com/ember-modifier/ember-modifier/pull/90

Ping @joshkg and @pzuraq .
