### ISSUE TITLE
Remove all custom destroy code in favor of destroyable

### ISSUE THREAD

**Issue by chriskrycho** [ember-modifier/ember-modifier#24]
The recently imported [RFC #0580](https://github.com/emberjs/rfcs/pull/580) added public API for destroying objects like this in terms of public API. It has been polyfilled for current releases via [ember-destroyable-polyfill](https://github.com/ember-polyfills/ember-destroyable-polyfill).

Relevant comments from #23:

- https://github.com/ember-modifier/ember-modifier/pull/23#discussion_r425458686
- https://github.com/ember-modifier/ember-modifier/pull/23#discussion_r425459417
- https://github.com/ember-modifier/ember-modifier/pull/23#discussion_r425463556
- https://github.com/ember-modifier/ember-modifier/pull/23#discussion_r425466652

These *should* cover the whole range of elements which can be reimplemented in terms of the new public API.

**Comment by simonihmig** [comment]
Given that Ember's current beta and canary releases already issue deprecations for the use of `setSourceDestroying()`, it would be nice get this sooner than later!

Especially as this causes some failing addon tests (set up to fail on deprecations) for me :wink:

**Comment by rwjblue** [comment]
Good point @simonihmig!

**Comment by jordpo** [comment]
I'm also seeing the `setSourceDestroying` deprecations now on ember-source@3.20.1.

**Comment by jordpo** [comment]
I also notice that `@glimmer/component` is using `setSourceDestroying` which is causing the bulk of my deprecations in my Octane app.

**Comment by richard-viney** [comment]
The `setSourceDestroying` deprecations seen when using. Glimmer components  were addressed in `ember-source@3.20.2` and `@glimmer/component@1.0.1`, however these ones coming from `ember-modifier` are still with us.

Is anyone already looking at this? If not, I could potentially look at doing a PR this week.

**Comment by rwjblue** [comment]
@richard-viney - Ya, I'm working on it. I hope to have a patch release for 1.x out with the deprecation fixed, and also to release 2.0.0 with the TS refactor.
