### ISSUE TITLE
3.2+: Class-based modifiers don't call `modify`?

### ISSUE THREAD

**Issue by kpfefferle** [ember-modifier/ember-modifier#251]
I'm following the [migration guide](https://github.com/ember-modifier/ember-modifier/blob/master/MIGRATIONS.md) to transition our modifiers to the new format, and I can't seem to get my class-based modifiers to call `modify` - not even on initial setup. My modifier is almost identical to one found in the README:

```ts
import Modifier, { ArgsFor, PositionalArgs, NamedArgs } from 'ember-modifier';
import { registerDestructor } from '@ember/destroyable';
import { inject as service } from '@ember/service';
import AnalyticsService from 'my-application/services/analytics';

interface TrackClickModifierSignature {
  Args: {
    Positional: [string];
    Named: Record<string, string>;
  };
  Element: Element;
}

export default class TrackClickModifier extends Modifier<TrackClickModifierSignature> {
  @service declare analytics: AnalyticsService;

  clickElement?: Element;
  name?: string;
  properties?: Record<string, string>;

  constructor(owner: unknown, args: ArgsFor<TrackClickModifierSignature>) {
    super(owner, args);
    registerDestructor(this, cleanup);
  }

  modify(
    element: Element,
    [name]: PositionalArgs<TrackClickModifierSignature>,
    properties: NamedArgs<TrackClickModifierSignature>
  ) {
    this.clickElement = element;
    this.name = name;
    this.properties = properties;
    cleanup(this);
    element.addEventListener('click', this.onClick, true);
  }

  onClick = () => {
    let { analytics, name, properties } = this;
    if (name) {
      analytics.trackEvent?.(name, properties);
    }
  };
}

function cleanup(instance: TrackClickModifier): void {
  instance.clickElement?.removeEventListener('click', instance.onClick, true);
}
```

Any guidance here, or is this a bug? If I put a `console.log` inside both `constructor` and `modify`, the `constructor` one gets called but not the `modify` one.

Thanks for the work on the new direction here @chriskrycho. Though it's a notable change, I do find these modifiers easier to understand now. I also appreciate the deprecation-based upgrade path, so I can merge my function-based modifier updates now as I await a resolution here for my class-based ones.

**Comment by chriskrycho** [comment]
Huh. That's odd. Exactly that is covered in the tests (a bunch)—can you put up a repo with a minimal reproduction? I’ll dig into it.

(Thanks for the kind words on the design direction!)

**Comment by pieter-v** [comment]
@kpfefferle @chriskrycho I had exact the same problem. It was caused by another dependency pulling in an older version  from ember-modifer.
Just look at the output of `yarn why ember-modifier`
You can solve this by adding a `resolutions` section to your `package.json`
```
  "resolutions": {
    "ember-modifier": "3.2.2"
  },
```

**Comment by kpfefferle** [comment]
Thanks @pieter-v - I somehow didn't think to check that 🤦

Class-based modifiers are now working! 🎉

**Comment by chriskrycho** [comment]
Ah, very good! Thanks for ID'ing the solution here, @pieter-v – should help others who hit this. Fundamentally, the problem is Ember CLI’s “Highlander rules” resolution: there can only be one version of a package like this resolved at runtime. Using `resolutions` (or similar) is sometimes important to make sure we get the *latest*.

**Comment by srsgores** [comment]
Yeah, we also had the same problem.  Have to add it in `overrides` for non-FB/Yarn users.

**Comment by rondale-sc** [comment]
@kpfefferle Great work. Saved my team some trouble. ❤️
