### ISSUE TITLE
Proposal: change `element` availability

### ISSUE THREAD

**Issue by chriskrycho** [ember-modifier/ember-modifier#29]
Right now, the class-based modifier specifies that the element is not available during the constructor or during `willDestroy`. The first of these is non-negotiable within the constraints of [the current modifier manager spec](https://github.com/emberjs/rfcs/blob/82305c4e502183578dcd371bc14ed7092c4f9852/text/0373-Element-Modifier-Managers.md#capabilities), and seems unlikely to change. However, the second is a *design choice*—I suspect it was made out of a worry that it would cause a memory leak, or perhaps to mirror the API from classic Ember components. Regardless, the modifier manager *forces* this:

https://github.com/ember-modifier/ember-modifier/blob/14d34b0edff357e089463c32e8b41a2b8f5823aa/addon/-private/class/modifier-manager.js#L29-L45

After discussing this with @rwjblue and @pzuraq, I propose we stop removing the element during `willDestroy`: it will be garbage collected properly during teardown of the modifier and element, and having this restriction in place substantially increases the complexity of both the docs and the types (see discussion on #23 for details on the latter), while providing no concrete benefit.

This does raise a question about the utility of having *both* `willRemove` and `willDestroy`. If we leave `this.element` in place for `willDestroy`, should we just deprecate `willRemove` as extraneous, and plan to remove it in a later major?

**Comment by rwjblue** [comment]
I am in favor of moving in this direction.

> This does raise a question about the utility of having both willRemove and willDestroy. If we leave this.element in place for willDestroy, should we just deprecate willRemove as extraneous, and plan to remove it in a later major?

IMHO, yes.
