### ISSUE TITLE
Run type tests nightly

### ISSUE THREAD

**Issue by chriskrycho** [ember-modifier/ember-modifier#32]
We should use Travis' [Cron Jobs](https://docs.travis-ci.com/user/cron-jobs/) feature to run *just* the type tests nightly, so we get the earliest possible signal of regression against upcoming TS versions.

**Comment by rwjblue** [comment]
Good idea, I scheduled a daily job to just run the full CI 🤷‍♂️

**Comment by chriskrycho** [comment]
I like it!
