### ISSUE TITLE
Named arguments should be more prominent in the API design and docs

### ISSUE THREAD

**Issue by elwayman02** [ember-modifier/ember-modifier#40]
## Premise

I would posit that named arguments are a more robust architecture for most things, and that designs like the `on` modifier are the exception where positional is preferred, rather than the rule. Most people should be building custom modifiers using named arguments, only switching to positional params where the use-case is very clearly more ergonomic.

## Problem Statement

In the entirety of the README for `ember-modifier`, there are very few examples of modifiers that use named arguments, and mostly it's just being shown within the context of other features, showing how it interacts with that functionality. Additionally, the fact that the named arguments are passed *after* positional arguments in the functional modifier design implies that positional arguments are the default.

These aspects of `ember-modifier` send a very strong signal that developers should be using positional params over named arguments wherever possible. We should rethink the design of `ember-modifier` and make sure to document it in a way that presents named arguments as the default pattern, with positional arguments as an option when and if you need them.

**Comment by rwjblue** [comment]
It isn't immediately clear to me that most modifiers will want to use positional or named arguments. When invoking with functions, do you tend to use positional arguments more or an options hash? For me, the answer is super simple: it depends :trollface:. Sometimes the one or two positional arguments are obvious (e.g. `on`), and other times using ordered arguments is just super confusing (too many, non-obvious ordering, etc). 

> In the entirety of the README for ember-modifier, there are very few examples of modifiers that use named arguments, and mostly it's just being shown within the context of other features, showing how it interacts with that functionality.

We should try to have ample examples of both styles (and mixed styles, using both positional and named).

> Additionally, the fact that the named arguments are passed after positional arguments in the functional modifier design implies that positional arguments are the default.

This is just how handlebars works, it isn't that one or the other is default. 

> These aspects of ember-modifier send a very strong signal that developers should be using positional params over named arguments wherever possible.

I personally don't agree with this conclusion, but I'm super keen to help clear this confusion. I think at least two actionable things here are:

1. Beef up the examples in the README and inline API docs to show relatively equal use of positional, named, and positional + named
2. Add some explicit language to the README explaining circumstances where you would prefer one form over the other, making it clear that neither is the "default" and that people need to use their brains 🤯.

**Comment by chriskrycho** [comment]
I have closed this as it is not actually a bug or issue. PRs improving the docs and showing more parity between named and positional arguments still welcome, of course!
