### ISSUE TITLE
Provide types

### ISSUE THREAD

**Issue by lolmaus** [ember-modifier/ember-modifier#43]
The npm package contains neither types nor TS sources, so it's impossible to make use of types in a consuming app/addon.

`ember-cli-typescript` has a guide that addresses this problem specifically:
https://ember-cli-typescript.com/versions/master/docs/ts-guide/with-addons

**Comment by lolmaus** [comment]
OK, I've realised that the conversion to TypeScript was done recently and the last published npm package is built from a non-TS version of the codebase.

Thank you for your effort!

Feel free to close this, but I believe it makes sense to keep it open until a TS-driven version of the package is published with types, in case anyone else gets frustrated like me. 😅

**Comment by chriskrycho** [comment]
Thanks for writing it up! New release inbound Soon™ with those.

**Comment by rwjblue** [comment]
🎉 https://github.com/ember-modifier/ember-modifier/releases/tag/v2.0.0
