### ISSUE TITLE
Error in willRemove halts page

### ISSUE THREAD

**Issue by jede** [ember-modifier/ember-modifier#44]
I don't know if this is intentional, but we are using an addon that caused an error in the `willRemove()` hook due to `willRemove()` was run too late after the route has changed and the new page had rendered. This seems to halt ember completely. No actions or anything works beyond that point. Maybe no errors should ever be thrown in `willRemove()`?

This is the line causing the issue I believe: https://github.com/ember-modifier/ember-modifier/blob/1da4e541ea8c627fd4bd0a3a7be913bb61e868cd/addon/-private/class/modifier-manager.ts#L55

The PR that fixes the error thrown in willRemove for reference: https://github.com/adopted-ember-addons/ember-sortable/pull/374

**Comment by rwjblue** [comment]
Since `modifier.willRemove` was being called directly from the manager, the entire rendering flow (and rendering transaction) gets derailed. I've updated the destruction flow over in #48 and I think that should resolve the issue.

Happy to reopen if that is mistaken...
