### ISSUE TITLE
Unknown blueprint: functional-modifier

### ISSUE THREAD

**Issue by AvinishSharma** [ember-modifier/ember-modifier#5]
The yarn install was successful for "ember-modifier" package but when trying to generate a functional modifier, I am getting unknown blueprint error.
>$ ember g functional-modifier my-modifier
Unknown blueprint: functional-modifier
this blueprint is not avail. in the list of "Available blueprints" on my machine.

**Comment by spencer516** [comment]
@AvinishSharma — that was an oversight! I just opened a PR to add that blueprint back in.

**Comment by pzuraq** [comment]
Fixed and released in v1.0.2, thanks @AvinishSharma for the bug report and @spencer516 for the fix!
