### ISSUE TITLE
Any special setup required in user land?

### ISSUE THREAD

**Issue by SergeAstapov** [ember-modifier/ember-modifier#52]
Is there any special setup required for `ember-modifier` v2 (which uses `ember-destroyable-polyfill` under the hood) in user land?

Tried to bump `ember-modifier` to v2 in https://github.com/DockYard/ember-in-viewport/pull/246 but build fails with error

```
Build Error (broccoli-persistent-filter:Babel > [Babel: ember-modifier]) in ember-modifier/-private/class/modifier-manager.ts
302
303/home/travis/build/DockYard/ember-in-viewport/ember-modifier/-private/class/modifier-manager.ts: @ember/destroyable does not have a destroy export
304  1 | import { capabilities } from '@ember/modifier';
305  2 | import { set } from '@ember/object';
306> 3 | import { destroy, registerDestructor } from '@ember/destroyable';
307    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
308  4 | 
309  5 | import ClassBasedModifier from './modifier';
310  6 | import { ModifierArgs } from 'ember-modifier/-private/interfaces';
```

quite puzzled as typescript setup mentioned in https://github.com/ember-polyfills/ember-destroyable-polyfill#typescript-usage [seem to be already done](https://github.com/ember-modifier/ember-modifier/blob/master/tsconfig.json#L30).

**Comment by SergeAstapov** [comment]
Same issue in https://github.com/lifeart/ember-click-outside-modifier/pull/2

**Comment by rwjblue** [comment]
Oiy. I think this is due to me missing `destroy` in the Ember-rfc176-data (and ember-destroyable-polyfill) PRs :facepalm:

**Comment by rwjblue** [comment]
Will be fixed by https://github.com/ember-modifier/ember-modifier/pull/54

**Comment by SergeAstapov** [comment]
Thank you @rwjblue for quick fix!
