### ISSUE TITLE
Build Issue with v2.0.0: @ember/destroyable does not have a destroy export

### ISSUE THREAD

**Issue by alexlafroscia** [ember-modifier/ember-modifier#53]
I’m seeing a build issue since the `ember-modifier@2.0.0` upgrade

```
Build Error (broccoli-persistent-filter:Babel > [Babel: ember-modifier]) in ember-modifier/-private/class/modifier-manager.ts

/home/runner/work/ember-iframe-resizer-modifier/ember-iframe-resizer-modifier/ember-modifier/-private/class/modifier-manager.ts: @ember/destroyable does not have a destroy export
  1 | import { capabilities } from '@ember/modifier';
  2 | import { set } from '@ember/object';
> 3 | import { destroy, registerDestructor } from '@ember/destroyable';
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  4 | 
  5 | import ClassBasedModifier from './modifier';
  6 | import { ModifierArgs } from 'ember-modifier/-private/interfaces';
```

You can see the results of trying to run `ember test` on some of my addons here

https://github.com/alexlafroscia/ember-iframe-resizer-modifier/runs/931614651
https://github.com/alexlafroscia/ember-resize-observer-modifier/runs/931619402

**Comment by alexlafroscia** [comment]
This seems particularly odd, as `1.0.1` of the destroyables polyfill certainly _does_ seem to have a `destroy` export...

**Comment by miguelcobain** [comment]
I'm also seeing this: https://travis-ci.org/github/peec/ember-css-transitions/builds/713736522

But I found that it only happens on the "Floating Dependencies" scenario.

**Comment by rwjblue** [comment]
Will be fixed by https://github.com/ember-modifier/ember-modifier/pull/54

**Comment by rwjblue** [comment]
Sorry about this y'all 😭, I made a mistake during implementation (of ember-cli-babel <-> ember-destroyable-polyfill support).

**Comment by alexlafroscia** [comment]
Thanks for the quick fix, @rwjblue !
