### ISSUE TITLE
Consider different names for class modifier "Arguments" hooks

### ISSUE THREAD

**Issue by dknutsen** [ember-modifier/ember-modifier#58]
I've been playing around with modifiers a bit recently and specifically ember-modifier (this is an awesome addon by the way, really love it) and I ran into a good but unexpected feature and it caused me a bit of confusion (see [this Discourse thread](https://discuss.emberjs.com/t/modifiers-updating-element-based-on-service-state/18154/4)).

Essentially because the didReceiveArguments/didUpdateArguments hooks specifically mention "arguments" I was expecting them to *only* be fired specifically on *argument* updates. What I was missing was the note in the README that says:

> As with functional modifiers, the lifecycle hooks of class modifiers are tracked. When they run, they any values they access will be added to the modifier, and the modifier will update if any of those values change.

The way it works is delightful and exactly what I wanted, however I think because the names of the hooks include "arguments" it implies the wrong thing about when they are fired (and even in the README it says "... and anytime the *arguments* are updated").

I think there are probably more intuitive names that would suggest that these hooks will be called when the arguments OR any consumed tracked props are updated and this could reduce some confusion as we look towards shipping this with Ember. I'm not sure exactly what the best name would be, `willUpdate` makes sense on some level but obviously that drags the component lifecycle hook history in with it... but I think maybe leaving the word "arguments" out would be very helpful regardless.

**Comment by chriskrycho** [comment]
@dknutsen I trust it will be encouraging to hear that this exact line of feedback (from you, from others, and from my own experience) was what motivated the complete redesign of the API to mirror helpers with having just the `modify()` hook. Thanks! Closing this accordingly. 🚀
