### ISSUE TITLE
Not clear that 1.0.3 isn't compatible with ember 3.20

### ISSUE THREAD

**Issue by Samsinite** [ember-modifier/ember-modifier#59]
Pretty minor, but I think it would be worthwhile to mention that 1.0.3 isn't compatible with ember 3.20. Upon upgrading to 3.20 started getting container issues in component tests where modifiers were used. I don't mind submitted a PR to add this to the readme, if that is something you would be interested in, if you are, how would you like it formatted?

**Comment by rwjblue** [comment]
I'm going to work on fixing 3.20 compat for the 1.x branch.

**Comment by rwjblue** [comment]
This should be resolved now. 🎉
