### ISSUE TITLE
Add class modifier blueprints

### ISSUE THREAD

**Issue by pzuraq** [ember-modifier/ember-modifier#7]
Currently we have functional modifier blueprints, but not blueprints class modifiers. We should add them to fill out the blueprint API.

**Comment by spencer516** [comment]
I’m on my phone, but I _think_ I included that in the PR. Should be:

`ember g modifier my-class-modifier -c`

Though, perhaps that should be the default? Or separate the commands out?

**Comment by pzuraq** [comment]
Oh well, that's what I get for not thoroughly reviewing 😅 thanks again!
