### ISSUE TITLE
Compatibility information in the readme seems wrong

### ISSUE THREAD

**Issue by Windvis** [ember-modifier/ember-modifier#72]
The README says that the minimum requirement for this addon is Ember 3.12, but it seems that CI is configured to test from v3.4. Could it be that the modification of the version requirement was an oversight during the [Ember blueprint update](https://github.com/ember-modifier/ember-modifier/commit/41d0a09b41e7f880c2a1582f399cacae2f877ce9#diff-efa7561fd196a5304c1c80012f1f6153c58faf5697ba3a59465ae7ce06b8e550R19)?

**Comment by chriskrycho** [comment]
Resolved; thanks again for reporting!
